addpath /home/phantom/projects/3dcar/CADcode/
addpath /home/phantom/projects/3dcar/CADcode/utils
addpath /home/phantom/projects/3dcar/CADcode/utils/model3d/


% written by sanja fidler

annotation = 1;
CLASS_NAME = 'car';
dataset_globals;
model_dir = CAD_MODELS_PATH;

files = dir(fullfile(model_dir, '*_mesh.mat'));
n_objects = length(files);
draw_points = 0;
show_texture = 1;
show_faces = 1;

width = 1100;
height = 600;
h_f = figure('Position',[150 80 width height]);
%set(h_f, 'Color', [1, 1, 1])
h_a = axes('Position',[0.01 0.04 0.99 1]); axis off;
if ~exist('obj_num', 'var')
   obj_num = 1;
else
   if obj_num > n_objects, obj_num = 1; end; 
end;
data = load(fullfile(model_dir, files(obj_num).name));
mesh = data.mesh; if isfield(data, 'mesh_viz'), mesh_viz = data.mesh_viz; else mesh_viz = []; end;
if isfield(data, 'transform'), transform = data.transform; else transform = []; end;
if isfield(data, 'model_file'), model_file = data.model_file; else model_file = fullfile(model_dir, files(obj_num).name); end;

% hack to get the name out
[path,name,ext] = fileparts(model_file);
orfiles = dir(strrep(path, '3ds', 'skp'));
instance_label = '';
if isfield(mesh, 'instance_name'), instance_label = mesh.instance_name; end;
    
h = viz_3D_model(mesh, [], draw_points, show_faces, show_texture);
box_text = [];
if (isfield(mesh, 'bbox') & ~isempty(mesh.bbox))
    box_text = 're-';
end;
[az,el]=view; camera.viewpoint = [az,el];
zoom(1/1.2);
axis vis3d;
%z = get(h_a, 'CameraViewAngle');
% info for aligning boxes (check transform_box function for details)
cp = [0,0,0];
center_type = 2;

big_button_spacing = 14;
small_button_spacing = 4;
cameratoolbar;
if exist('CLASS_NAME', 'var')
   class_label = CLASS_NAME;
else
    class_label = 'car';
end;

pos = 10; w = 45;
uicontrol('Style', 'pushbutton', 'String', '<<', ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['obj_num = obj_num-1; if obj_num<1, obj_num=n_objects; end;' ...
                       'data = load(fullfile(model_dir, files(obj_num).name));' ...
                       'mesh = data.mesh; if isfield(data, ''mesh_viz''), mesh_viz = data.mesh_viz; else mesh_viz = []; end;'...
                       'if isfield(data, ''transform''), transform = data.transform; else transform = []; end;'...
                       'if isfield(data, ''model_file''), model_file = data.model_file; else model_file = fullfile(model_dir, files(obj_num).name); end;'...
                       'if isfield(mesh, ''instance_name''), instance_label = mesh.instance_name; set(hObjInstance, ''BackgroundColor'', [0.4,0.6,1]);'... 
                       'else set(hObjInstance, ''BackgroundColor'', [1,0.2,0.6]); instance_label =''''; try, file=dir(strrep(model_file,''3ds'',''skp'')); b = file(1).bytes; for i=1:length(orfiles), if orfiles(i).bytes==b, instance_label = orfiles(i).name; [path,instance_label,ext] = fileparts(strrep(instance_label, ''_'', ''-'')); end; end; end; end;'...
                       '[az,el]=view; camera.viewpoint = [az,el]; cam_pos = campos;' ...
                       'dims = 0; if isfield(mesh, ''dims''), dims = mesh.dims; end; set(hObjHeight, ''String'', sprintf(''%0.1f '', dims));'...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;' ...
                       'if (annotation),'...
                       'if (isfield(mesh, ''bbox'') & ~isempty(mesh.bbox))'...  
                       '   box_text = ''re-'';'...
                       'else'...
                       '   box_text = [];'...
                       '   set(hBox, ''String'', [box_text ''compute box'']);'...
                       'end;'...
                       'end;'...
                       'filename = files(obj_num).name; [path, name, ext] = fileparts(filename); p = findstr(name, ''_mesh''); if numel(p), name = name(1, 1:p(end)-1); end;' ...
                       'set(hObjname, ''string'', name);'...
                       'if isfield(mesh, ''class_name''), set(hObjClass, ''String'', mesh.class_name); set(hObjClass, ''BackgroundColor'', [0.4,0.6,1]); else set(hObjClass, ''BackgroundColor'', [1,0.2,0.6]); end;'...
                       'set(hObjInstance, ''String'', instance_label);'...
                   ]);

pos = pos + w + small_button_spacing;                   
uicontrol('Style', 'pushbutton', 'String', '>>', ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['obj_num = obj_num+1; if obj_num>n_objects, obj_num=1; end;' ...
                       'data = load(fullfile(model_dir, files(obj_num).name));' ...
                       'mesh = data.mesh; if isfield(data, ''mesh_viz''), mesh_viz = data.mesh_viz; else mesh_viz = []; end;'...
                       'if isfield(data, ''transform''), transform = data.transform; else transform = []; end;'...
                       'if isfield(data, ''model_file''), model_file = data.model_file; else model_file = fullfile(model_dir, files(obj_num).name); end;'...
                       'if isfield(mesh, ''instance_name''), instance_label = mesh.instance_name; set(hObjInstance, ''BackgroundColor'', [0.4,0.6,1]);'... 
                       'else set(hObjInstance, ''BackgroundColor'', [1,0.2,0.6]); instance_label =''''; try, file=dir(strrep(model_file,''3ds'',''skp'')); b = file(1).bytes; for i=1:length(orfiles), if orfiles(i).bytes==b, instance_label = orfiles(i).name; [path,instance_label,ext] = fileparts(strrep(instance_label, ''_'', ''-'')); end; end; end; end;'...
                       'dims = 0; if isfield(mesh, ''dims''), dims = mesh.dims; end; set(hObjHeight, ''String'', sprintf(''%0.1f '', dims));'...
                       '[az,el]=view; camera.viewpoint = [az,el]; cam_pos = campos;' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;' ...
                       'if (annotation),'...
                       'if (isfield(mesh, ''bbox'') & ~isempty(mesh.bbox))'...  
                       '   box_text = ''re-'';'...
                       'else'...
                       '   box_text = [];'...
                       '   set(hBox, ''String'', [box_text ''compute box'']);'...
                       'end;'...
                       'end;'...
                       'filename = files(obj_num).name; [path, name, ext] = fileparts(filename); p = findstr(name, ''_mesh''); if numel(p), name = name(1, 1:p(end)-1); end;' ...' ...
                       'set(hObjname, ''string'', name);'...
                       'if isfield(mesh, ''class_name''), set(hObjClass, ''String'', mesh.class_name); set(hObjClass, ''BackgroundColor'', [0.4,0.6,1]); else set(hObjClass, ''BackgroundColor'', [1,0.2,0.6]); end;'...
                       'set(hObjInstance, ''String'', instance_label);'...
                       ]);
                            
if (annotation)                   
pos = pos + w + small_button_spacing;  
w = 85;
hBox = uicontrol('Style', 'pushbutton', 'String', [box_text 'compute box'], ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['mesh_old = mesh;'...
                       'fprintf(''Computing box...\n'');'...
                       '[cornerpoints, bbox] = fit_3D_bbox(mesh);'...
                       'mesh.bbox = bbox;'...
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;' ...
                       'user_entry = input(''keep new box? [y/n] '', ''s'');'...
                       'if strcmp(user_entry, ''y'')'...
                       '   filename = files(obj_num).name;' ...
                       '   save(fullfile(model_dir, files(obj_num).name), ''mesh'', ''mesh_viz'', ''transform'', ''model_file'');'...
                       '   box_text = ''re-''; if annotation, set(hBox, ''String'', [box_text ''compute box'']); end;'...
                       'else'...
                       '   mesh = mesh_old;'...
                       '   [az,el]=view; camera.viewpoint = [az,el];' ...
                       '   h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;' ...
                       'end;'...
                       'set(hObjname, ''string'', name);']);  
end;                   

pos = pos + w + small_button_spacing; 
w = 74;    
hObjtexture = uicontrol('Style', 'radiobutton', 'String', 'show text.', 'Value', show_texture, ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['show_texture = get(hObjtexture,''Value'');' ... 
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;']);

pos = pos + w + small_button_spacing; 
w = 75;    
hObjBox = uicontrol('Style', 'radiobutton', 'String', 'show box', 'Value', show_faces>0, ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['show_box = get(hObjbox,''Value'');' ... 
                       'show_faces = show_box;'...
                       'if get(hObjbox,''Value'')==1 & show_box==1, show_faces=2; end;'...
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;']);

                   
pos = pos + w + small_button_spacing; 
w = 80;    
hObjbox = uicontrol('Style', 'radiobutton', 'String', 'show faces', 'Value', show_faces==2, ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['show_faces = get(hObjbox,''Value'') + 1;' ... 
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;']);
                   
if annotation                   
pos = pos + w + small_button_spacing; 
w = 35;    
uicontrol('style','text','string','front: ','position',[pos-5,  40, w, 16],'fontsize',9, 'BackgroundColor', [1,1,1], 'ForegroundColor', [0,0,0]); 
%pos = pos + w + small_button_spacing;
w = 25;
hObjfront = uicontrol('Style', 'edit', 'String', '1', ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['f = get(hObjfront,''String'');' ...
                       'g = get(hObjground,''String'');' ...
                       'try, f = str2num(f); catch, f = 1; end;' ...
                       'try, g = str2num(g); catch, g = 2; end;' ...
                       'mesh.bbox = number_box_faces(mesh.bbox, [f, g]'');' ...
                       'set(hObjfront,''String'', ''1'');'...
                       'set(hObjground,''String'', ''2'');'...
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;'...
                       ]);
                   
pos = pos + w + 2* small_button_spacing; 
w = 45;                    
uicontrol('style','text','string','ground: ','position',[pos-10,  40, w, 16],'fontsize',9, 'BackgroundColor', [1,1,1], 'ForegroundColor', [0,0,0]); 
%pos = pos + w + small_button_spacing; 
w = 25;
hObjground = uicontrol('Style', 'edit', 'String', '2', ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['f = get(hObjfront,''String'');' ...
                       'g = get(hObjground,''String'');' ...
                       'try, f = str2num(f); catch, f = 1; end;' ...
                       'try, g = str2num(g); catch, g = 2; end;' ...
                       'mesh.bbox = number_box_faces(mesh.bbox, [f, g]'');' ...
                       'set(hObjfront,''String'', ''1'');'...
                       'set(hObjground,''String'', ''2'');'...
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;'...
                       ]);    
end;

pos = pos + w + small_button_spacing; 
w = 40;                    
uicontrol('style','text','string','class: ','position',[pos-5,  40, w, 16],'fontsize',9, 'BackgroundColor', [1,1,1], 'ForegroundColor', [0,0,0]); 
%pos = pos + w + small_button_spacing; 
w = 75;
hObjClass = uicontrol('Style', 'edit', 'String', class_label, 'FontSize', 10, 'BackgroundColor', [0.4,0.6,1], 'FontWeight', 'bold', ...
          'Position', [pos 10 w 30]);
      
pos = pos + w + small_button_spacing; 
w = 35;                    
uicontrol('style','text','string','inst.: ','position',[pos-5,  40, w, 16],'fontsize',9, 'BackgroundColor', [1,1,1], 'ForegroundColor', [0,0,0]); 
%pos = pos + w + small_button_spacing; 
w = 115;
hObjInstance = uicontrol('Style', 'edit', 'String', instance_label, 'FontSize', 10, 'BackgroundColor', [0.4,0.6,1], 'FontWeight', 'bold', ...
          'Position', [pos 10 w 30]);  
      
pos = pos + w + small_button_spacing; 
w = 110;                    
uicontrol('style','text','string','dims: width, height, length','position',[pos-10,  40, w, 16],'fontsize',9, 'BackgroundColor', [1,1,1], 'ForegroundColor', [0,0,0]); 
%pos = pos + w + small_button_spacing; 
w = 100;
dims = 0;
if isfield(mesh, 'dims')
    dims = mesh.dims;
end;
% [width, height, length]
hObjHeight = uicontrol('Style', 'edit', 'String', sprintf('%0.0f ',dims), 'FontSize', 10, 'BackgroundColor', [0.4,0.6,1], 'FontWeight', 'bold', ...
          'Position', [pos 10 w 30]);


if isfield(mesh, 'class_name'), set(hObjClass, 'BackgroundColor', [0.4,0.6,1]); else set(hObjClass, 'BackgroundColor', [1,0.2,0.6]); end;
pos = pos + w + small_button_spacing; 
w = 55;
hBoxSave = uicontrol('Style', 'pushbutton', 'String', 'Save', ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['t = transform_box(cp, mesh.bbox, center_type, CLASS_NAME); clear(''transform''); transform{1} = t;' ...
                       'mesh.transform = transform;' ...
                       'mesh.class_name = get(hObjClass, ''String'');'...
                       'mesh.instance_name = get(hObjInstance, ''String'');'...
                       'try, dims = get(hObjHeight, ''String''); dims = str2num(dims); mesh.dims = dims; end;'...
                       'set(hObjClass, ''BackgroundColor'', [0.4,0.6,1]);'...
                       'set(hObjInstance, ''BackgroundColor'', [0.4,0.6,1]);'...
                       'save(fullfile(model_dir, files(obj_num).name), ''mesh'', ''mesh_viz'', ''transform'', ''model_file'');']);
                   
w1 = 65; 
pos = width - w1 - 10;    
uicontrol('Style', 'pushbutton', 'String', 'Exit', ...
          'Position', [pos 10 w1 30], ... 
          'Callback', 'close all;');     
      
pos = pos - w1 - small_button_spacing - 10; 
w = 75;
hBoxSave = uicontrol('Style', 'pushbutton', 'String', 'Delete model.', ...
          'Position', [pos 10 w 30], ... 
          'Callback', ['delete(fullfile(model_dir, files(obj_num).name));' ...
                       'try, delete(fullfile(model_dir, ''..'', ''3ds'', [name ''.3ds''])); end;'...
                       'files = dir(fullfile(model_dir, ''*.mat'')); n_objects = length(files);'...
                       'obj_num = obj_num-1; if obj_num<1, obj_num=n_objects; end;' ...
                       'data = load(fullfile(model_dir, files(obj_num).name));' ...
                       'mesh = data.mesh; if isfield(data, ''mesh_viz''), mesh_viz = data.mesh_viz; else mesh_viz = []; end;'...
                       'if isfield(data, ''transform''), transform = data.transform; else transform = []; end;'...
                       'if isfield(data, ''model_file''), model_file = data.model_file; else model_file = fullfile(model_dir, files(obj_num).name); end;'...
                       '[az,el]=view; camera.viewpoint = [az,el];' ...
                       'h = viz_3D_model(mesh, camera, draw_points, show_faces, show_texture); zoom(1/1.2); axis vis3d;' ...
                       'if (annotation),'...
                       'if (isfield(mesh, ''bbox'') & ~isempty(mesh.bbox))'...  
                       '   box_text = ''re-'';'...
                       'else'...
                       '   box_text = [];'...
                       '   set(hBox, ''String'', [box_text ''compute box'']);'...
                       'end;'...
                       'end;'...
                       'filename = files(obj_num).name; [path, name, ext] = fileparts(filename); p = findstr(name, ''_mesh''); if numel(p), name = name(1, 1:p(end)-1); end;' ...
                       'set(hObjname, ''string'', name);'...
                       'if isfield(mesh, ''class_name''), set(hObjClass, ''String'', mesh.class_name); end;']);                     
                   

filename = files(obj_num).name;
[path, name, ext] = fileparts(filename);
p = findstr(name, '_mesh'); if numel(p), name = name(1, 1:p(end)-1); end;
hObjname = uicontrol('style','text','string',name,'position',[10, 45, 250, 30],'fontsize',15, 'fontweight', 'bold','BackgroundColor', [1,1,1], 'ForegroundColor', [0,0,0], 'HorizontalAlignment', 'left');                   

